import { q } from './ident.ts';

function assertIdent(name: string): string {
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name)) {
    throw new Error(`Invalid SQL identifier: ${name}`);
  }
  return name;
}

/** DDL for schema `ssc` (or a test schema). Matches schema/SSC_Attendance_Fresh_Database_Schema.sql */
export function schemaStatements(schema = 'ssc'): string[] {
  const s = assertIdent(schema);
  return [
    `CREATE SCHEMA IF NOT EXISTS ${s}`,
    `SET search_path TO ${s}`,
    `CREATE OR REPLACE FUNCTION new_row_version()
     RETURNS bytea
     LANGUAGE sql
     AS $$
       SELECT decode(substr(md5(random()::text || clock_timestamp()::text), 1, 16), 'hex')
     $$`,
    `CREATE OR REPLACE FUNCTION bump_row_version()
     RETURNS trigger
     LANGUAGE plpgsql
     AS $$
     BEGIN
       NEW.${q('rowVersion')} := new_row_version();
       RETURN NEW;
     END;
     $$`,
    `DROP VIEW IF EXISTS v_attendance_session_status`,
    `CREATE TABLE IF NOT EXISTS ${q('Users')} (
      ${q('userId')} integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username varchar(100) NOT NULL,
      ${q('passwordHash')} text NOT NULL,
      ${q('displayName')} varchar(200) NOT NULL,
      role varchar(20) NOT NULL,
      ${q('isActive')} boolean NOT NULL DEFAULT true,
      ${q('createdAtUtc')} timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      ${q('updatedAtUtc')} timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      ${q('rowVersion')} bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_users_username UNIQUE (username),
      CONSTRAINT ck_users_username CHECK (char_length(btrim(username)) > 0),
      CONSTRAINT ck_users_name CHECK (char_length(btrim(${q('displayName')})) > 0),
      CONSTRAINT ck_users_role CHECK (role IN ('superadmin', 'moderator', 'student'))
    )`,
    `CREATE TABLE IF NOT EXISTS ${q('AcademicYears')} (
      ${q('academicYearId')} bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ${q('yearCode')} varchar(30) NOT NULL,
      ${q('yearName')} varchar(100) NOT NULL,
      ${q('startsOn')} date NOT NULL,
      ${q('endsOn')} date NOT NULL,
      ${q('isActive')} boolean NOT NULL DEFAULT true,
      ${q('createdAtUtc')} timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      ${q('rowVersion')} bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_academic_years_code UNIQUE (${q('yearCode')}),
      CONSTRAINT ck_academic_years_dates CHECK (${q('startsOn')} <= ${q('endsOn')})
    )`,
    `CREATE TABLE IF NOT EXISTS ${q('AcademicTerms')} (
      ${q('academicTermId')} bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ${q('academicYearId')} bigint NOT NULL,
      ${q('termCode')} varchar(30) NOT NULL,
      ${q('termName')} varchar(100) NOT NULL,
      ${q('startsOn')} date NOT NULL,
      ${q('endsOn')} date NOT NULL,
      ${q('isActive')} boolean NOT NULL DEFAULT true,
      ${q('createdAtUtc')} timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      ${q('rowVersion')} bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_academic_terms_code UNIQUE (${q('academicYearId')}, ${q('termCode')}),
      CONSTRAINT fk_academic_terms_year FOREIGN KEY (${q('academicYearId')})
        REFERENCES ${q('AcademicYears')} (${q('academicYearId')}),
      CONSTRAINT ck_academic_terms_dates CHECK (${q('startsOn')} <= ${q('endsOn')})
    )`,
    `CREATE TABLE IF NOT EXISTS ${q('AcademicPrograms')} (
      ${q('academicProgramId')} bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ${q('programCode')} varchar(30) NOT NULL,
      ${q('programName')} varchar(200) NOT NULL,
      ${q('isActive')} boolean NOT NULL DEFAULT true,
      ${q('createdAtUtc')} timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      ${q('rowVersion')} bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_academic_programs_code UNIQUE (${q('programCode')})
    )`,
    `CREATE TABLE IF NOT EXISTS ${q('Sections')} (
      ${q('sectionId')} bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ${q('academicTermId')} bigint NOT NULL,
      ${q('academicProgramId')} bigint NOT NULL,
      ${q('yearLevel')} smallint NOT NULL,
      ${q('sectionCode')} varchar(30) NOT NULL,
      ${q('sectionName')} varchar(100) NOT NULL,
      ${q('isActive')} boolean NOT NULL DEFAULT true,
      ${q('createdAtUtc')} timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      ${q('rowVersion')} bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_sections_context UNIQUE (${q('academicTermId')}, ${q('academicProgramId')}, ${q('yearLevel')}, ${q('sectionId')}),
      CONSTRAINT uq_sections_code UNIQUE (${q('academicTermId')}, ${q('academicProgramId')}, ${q('sectionCode')}),
      CONSTRAINT fk_sections_term FOREIGN KEY (${q('academicTermId')})
        REFERENCES ${q('AcademicTerms')} (${q('academicTermId')}),
      CONSTRAINT fk_sections_program FOREIGN KEY (${q('academicProgramId')})
        REFERENCES ${q('AcademicPrograms')} (${q('academicProgramId')}),
      CONSTRAINT ck_sections_year_level CHECK (${q('yearLevel')} BETWEEN 1 AND 20)
    )`,
    `CREATE TABLE IF NOT EXISTS ${q('Students')} (
      ${q('studentId')} bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ${q('studentNumber')} varchar(50) NOT NULL,
      ${q('userId')} integer NULL,
      ${q('firstName')} varchar(100) NOT NULL,
      ${q('middleName')} varchar(100) NULL,
      ${q('lastName')} varchar(100) NOT NULL,
      suffix varchar(30) NULL,
      ${q('photoUrl')} text NULL,
      ${q('isActive')} boolean NOT NULL DEFAULT true,
      ${q('createdAtUtc')} timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      ${q('updatedAtUtc')} timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      ${q('rowVersion')} bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_students_number UNIQUE (${q('studentNumber')}),
      CONSTRAINT fk_students_user FOREIGN KEY (${q('userId')}) REFERENCES ${q('Users')} (${q('userId')}),
      CONSTRAINT ck_students_number CHECK (char_length(btrim(${q('studentNumber')})) > 0),
      CONSTRAINT ck_students_name CHECK (
        char_length(btrim(${q('firstName')})) > 0 AND char_length(btrim(${q('lastName')})) > 0
      )
    )`,
    `CREATE UNIQUE INDEX IF NOT EXISTS ux_students_login
      ON ${q('Students')} (${q('userId')})
      WHERE ${q('userId')} IS NOT NULL`,
    `CREATE TABLE IF NOT EXISTS ${q('StudentEnrollments')} (
      ${q('studentEnrollmentId')} bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ${q('studentId')} bigint NOT NULL,
      ${q('academicTermId')} bigint NOT NULL,
      ${q('academicProgramId')} bigint NOT NULL,
      ${q('sectionId')} bigint NULL,
      ${q('yearLevel')} smallint NOT NULL,
      ${q('enrollmentStatusCode')} varchar(15) NOT NULL DEFAULT 'ENROLLED',
      ${q('effectiveFromUtc')} timestamptz(3) NOT NULL,
      ${q('effectiveToUtc')} timestamptz(3) NULL,
      ${q('createdAtUtc')} timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      ${q('rowVersion')} bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_student_enrollments_context UNIQUE (
        ${q('academicTermId')}, ${q('studentEnrollmentId')}, ${q('studentId')}
      ),
      CONSTRAINT fk_student_enrollments_student FOREIGN KEY (${q('studentId')})
        REFERENCES ${q('Students')} (${q('studentId')}) ON DELETE CASCADE,
      CONSTRAINT fk_student_enrollments_term FOREIGN KEY (${q('academicTermId')})
        REFERENCES ${q('AcademicTerms')} (${q('academicTermId')}),
      CONSTRAINT fk_student_enrollments_program FOREIGN KEY (${q('academicProgramId')})
        REFERENCES ${q('AcademicPrograms')} (${q('academicProgramId')}),
      CONSTRAINT fk_student_enrollments_section FOREIGN KEY (
        ${q('academicTermId')}, ${q('academicProgramId')}, ${q('yearLevel')}, ${q('sectionId')}
      ) REFERENCES ${q('Sections')} (${q('academicTermId')}, ${q('academicProgramId')}, ${q('yearLevel')}, ${q('sectionId')}),
      CONSTRAINT ck_student_enrollments_year CHECK (${q('yearLevel')} BETWEEN 1 AND 20),
      CONSTRAINT ck_student_enrollments_status CHECK (
        ${q('enrollmentStatusCode')} IN ('ENROLLED', 'WITHDRAWN', 'COMPLETED', 'CANCELLED')
      ),
      CONSTRAINT ck_student_enrollments_dates CHECK (
        ${q('effectiveToUtc')} IS NULL OR ${q('effectiveToUtc')} > ${q('effectiveFromUtc')}
      )
    )`,
    `CREATE UNIQUE INDEX IF NOT EXISTS ux_student_enrollments_current
      ON ${q('StudentEnrollments')} (${q('studentId')}, ${q('academicTermId')})
      WHERE ${q('effectiveToUtc')} IS NULL`,
    `CREATE INDEX IF NOT EXISTS ix_student_enrollments_roster
      ON ${q('StudentEnrollments')} (${q('academicTermId')}, ${q('academicProgramId')}, ${q('sectionId')})
      INCLUDE (${q('studentId')}, ${q('studentEnrollmentId')}, ${q('enrollmentStatusCode')}, ${q('effectiveFromUtc')}, ${q('effectiveToUtc')})`,
    `CREATE TABLE IF NOT EXISTS ${q('Events')} (
      ${q('eventId')} bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ${q('academicTermId')} bigint NOT NULL,
      ${q('eventCode')} varchar(50) NOT NULL,
      ${q('eventName')} varchar(200) NOT NULL,
      description varchar(2000) NULL,
      venue varchar(300) NULL,
      ${q('eventDate')} date NOT NULL,
      ${q('eventStatusCode')} varchar(12) NOT NULL DEFAULT 'DRAFT',
      ${q('createdByUserId')} integer NOT NULL,
      ${q('createdAtUtc')} timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      ${q('updatedAtUtc')} timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      ${q('rowVersion')} bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_events_context UNIQUE (${q('eventId')}, ${q('academicTermId')}),
      CONSTRAINT uq_events_code UNIQUE (${q('eventCode')}),
      CONSTRAINT fk_events_term FOREIGN KEY (${q('academicTermId')})
        REFERENCES ${q('AcademicTerms')} (${q('academicTermId')}),
      CONSTRAINT fk_events_creator FOREIGN KEY (${q('createdByUserId')})
        REFERENCES ${q('Users')} (${q('userId')}),
      CONSTRAINT ck_events_status CHECK (
        ${q('eventStatusCode')} IN ('DRAFT', 'PUBLISHED', 'CLOSED', 'CANCELLED')
      )
    )`,
    `CREATE TABLE IF NOT EXISTS ${q('EventSessions')} (
      ${q('eventSessionId')} bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ${q('eventId')} bigint NOT NULL,
      ${q('academicTermId')} bigint NOT NULL,
      ${q('sessionCode')} varchar(30) NOT NULL,
      ${q('sessionName')} varchar(100) NOT NULL,
      ${q('startsAtUtc')} timestamptz(3) NOT NULL,
      ${q('endsAtUtc')} timestamptz(3) NOT NULL,
      ${q('checkInOpensAtUtc')} timestamptz(3) NOT NULL,
      ${q('checkInClosesAtUtc')} timestamptz(3) NOT NULL,
      ${q('lateAfterUtc')} timestamptz(3) NOT NULL,
      ${q('checkOutOpensAtUtc')} timestamptz(3) NOT NULL,
      ${q('checkOutClosesAtUtc')} timestamptz(3) NOT NULL,
      ${q('requiresCheckOut')} boolean NOT NULL DEFAULT true,
      ${q('minimumMinutes')} integer NOT NULL DEFAULT 0,
      ${q('isClosed')} boolean NOT NULL DEFAULT false,
      ${q('sortOrder')} integer NOT NULL DEFAULT 0,
      ${q('createdAtUtc')} timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      ${q('rowVersion')} bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_event_sessions_context UNIQUE (${q('eventSessionId')}, ${q('academicTermId')}),
      CONSTRAINT uq_event_sessions_code UNIQUE (${q('eventId')}, ${q('sessionCode')}),
      CONSTRAINT fk_event_sessions_event FOREIGN KEY (${q('eventId')}, ${q('academicTermId')})
        REFERENCES ${q('Events')} (${q('eventId')}, ${q('academicTermId')}) ON DELETE CASCADE,
      CONSTRAINT ck_event_sessions_dates CHECK (
        ${q('startsAtUtc')} < ${q('endsAtUtc')}
        AND ${q('checkInOpensAtUtc')} <= ${q('startsAtUtc')}
        AND ${q('checkInClosesAtUtc')} >= ${q('startsAtUtc')}
        AND ${q('checkInClosesAtUtc')} <= ${q('endsAtUtc')}
        AND ${q('lateAfterUtc')} >= ${q('startsAtUtc')}
        AND ${q('lateAfterUtc')} <= ${q('checkInClosesAtUtc')}
        AND ${q('checkOutOpensAtUtc')} >= ${q('startsAtUtc')}
        AND ${q('checkOutOpensAtUtc')} <= ${q('checkOutClosesAtUtc')}
        AND ${q('checkOutClosesAtUtc')} >= ${q('endsAtUtc')}
      ),
      CONSTRAINT ck_event_sessions_minutes CHECK (
        ${q('minimumMinutes')} >= 0 AND (${q('requiresCheckOut')} = true OR ${q('minimumMinutes')} = 0)
      )
    )`,
    `CREATE TABLE IF NOT EXISTS ${q('EventParticipants')} (
      ${q('eventParticipantId')} bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ${q('eventSessionId')} bigint NOT NULL,
      ${q('academicTermId')} bigint NOT NULL,
      ${q('studentEnrollmentId')} bigint NOT NULL,
      ${q('studentId')} bigint NOT NULL,
      ${q('isRequired')} boolean NOT NULL DEFAULT true,
      ${q('addedByUserId')} integer NOT NULL,
      ${q('addedAtUtc')} timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      CONSTRAINT uq_event_participants_student_session UNIQUE (${q('eventSessionId')}, ${q('studentId')}),
      CONSTRAINT fk_event_participants_session FOREIGN KEY (${q('eventSessionId')}, ${q('academicTermId')})
        REFERENCES ${q('EventSessions')} (${q('eventSessionId')}, ${q('academicTermId')}) ON DELETE CASCADE,
      CONSTRAINT fk_event_participants_enrollment FOREIGN KEY (
        ${q('academicTermId')}, ${q('studentEnrollmentId')}, ${q('studentId')}
      ) REFERENCES ${q('StudentEnrollments')} (${q('academicTermId')}, ${q('studentEnrollmentId')}, ${q('studentId')})
        ON DELETE CASCADE,
      CONSTRAINT fk_event_participants_actor FOREIGN KEY (${q('addedByUserId')})
        REFERENCES ${q('Users')} (${q('userId')})
    )`,
    `CREATE INDEX IF NOT EXISTS ix_event_participants_student
      ON ${q('EventParticipants')} (${q('studentId')}, ${q('eventSessionId')})`,
    `CREATE TABLE IF NOT EXISTS ${q('AttendanceRecords')} (
      ${q('attendanceRecordId')} bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ${q('eventParticipantId')} bigint NOT NULL,
      ${q('checkedInAtUtc')} timestamptz(3) NULL,
      ${q('checkedOutAtUtc')} timestamptz(3) NULL,
      ${q('isExcused')} boolean NOT NULL DEFAULT false,
      ${q('excuseReason')} varchar(500) NULL,
      ${q('lastChangedByUserId')} integer NOT NULL,
      ${q('lastChangedAtUtc')} timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      ${q('rowVersion')} bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_attendance_records_participant UNIQUE (${q('eventParticipantId')}),
      CONSTRAINT fk_attendance_records_participant FOREIGN KEY (${q('eventParticipantId')})
        REFERENCES ${q('EventParticipants')} (${q('eventParticipantId')}) ON DELETE CASCADE,
      CONSTRAINT fk_attendance_records_actor FOREIGN KEY (${q('lastChangedByUserId')})
        REFERENCES ${q('Users')} (${q('userId')}),
      CONSTRAINT ck_attendance_records_order CHECK (
        ${q('checkedOutAtUtc')} IS NULL
        OR (${q('checkedInAtUtc')} IS NOT NULL AND ${q('checkedOutAtUtc')} >= ${q('checkedInAtUtc')})
      ),
      CONSTRAINT ck_attendance_records_excuse CHECK (
        (${q('isExcused')} = false AND ${q('excuseReason')} IS NULL)
        OR (
          ${q('isExcused')} = true
          AND ${q('excuseReason')} IS NOT NULL
          AND char_length(btrim(${q('excuseReason')})) > 0
        )
      )
    )`,
    `CREATE TABLE IF NOT EXISTS ${q('AttendanceCorrections')} (
      ${q('attendanceCorrectionId')} bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ${q('attendanceRecordId')} bigint NOT NULL,
      ${q('expectedRowVersion')} bytea NOT NULL,
      ${q('proposedCheckInAtUtc')} timestamptz(3) NULL,
      ${q('proposedCheckOutAtUtc')} timestamptz(3) NULL,
      ${q('proposedIsExcused')} boolean NOT NULL,
      ${q('proposedExcuseReason')} varchar(500) NULL,
      reason varchar(1000) NOT NULL,
      ${q('requestedByUserId')} integer NOT NULL,
      ${q('requestedAtUtc')} timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      ${q('correctionStatusCode')} varchar(10) NOT NULL DEFAULT 'PENDING',
      ${q('reviewedByUserId')} integer NULL,
      ${q('reviewedAtUtc')} timestamptz(3) NULL,
      ${q('reviewNote')} varchar(1000) NULL,
      ${q('rowVersion')} bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_attendance_corrections_context UNIQUE (
        ${q('attendanceRecordId')}, ${q('attendanceCorrectionId')}
      ),
      CONSTRAINT fk_attendance_corrections_record FOREIGN KEY (${q('attendanceRecordId')})
        REFERENCES ${q('AttendanceRecords')} (${q('attendanceRecordId')}) ON DELETE CASCADE,
      CONSTRAINT fk_attendance_corrections_requester FOREIGN KEY (${q('requestedByUserId')})
        REFERENCES ${q('Users')} (${q('userId')}),
      CONSTRAINT fk_attendance_corrections_reviewer FOREIGN KEY (${q('reviewedByUserId')})
        REFERENCES ${q('Users')} (${q('userId')}),
      CONSTRAINT ck_attendance_corrections_status CHECK (
        ${q('correctionStatusCode')} IN ('PENDING', 'APPLIED', 'REJECTED')
      ),
      CONSTRAINT ck_attendance_corrections_reason CHECK (char_length(btrim(reason)) > 0),
      CONSTRAINT ck_attendance_corrections_order CHECK (
        ${q('proposedCheckOutAtUtc')} IS NULL
        OR (
          ${q('proposedCheckInAtUtc')} IS NOT NULL
          AND ${q('proposedCheckOutAtUtc')} >= ${q('proposedCheckInAtUtc')}
        )
      ),
      CONSTRAINT ck_attendance_corrections_excuse CHECK (
        (${q('proposedIsExcused')} = false AND ${q('proposedExcuseReason')} IS NULL)
        OR (
          ${q('proposedIsExcused')} = true
          AND ${q('proposedExcuseReason')} IS NOT NULL
          AND char_length(btrim(${q('proposedExcuseReason')})) > 0
        )
      ),
      CONSTRAINT ck_attendance_corrections_review CHECK (
        (${q('correctionStatusCode')} = 'PENDING' AND ${q('reviewedByUserId')} IS NULL AND ${q('reviewedAtUtc')} IS NULL)
        OR (
          ${q('correctionStatusCode')} IN ('APPLIED', 'REJECTED')
          AND ${q('reviewedByUserId')} IS NOT NULL
          AND ${q('reviewedAtUtc')} IS NOT NULL
          AND ${q('reviewedAtUtc')} >= ${q('requestedAtUtc')}
          AND ${q('reviewedByUserId')} <> ${q('requestedByUserId')}
        )
      )
    )`,
    `CREATE INDEX IF NOT EXISTS ix_attendance_corrections_queue
      ON ${q('AttendanceCorrections')} (${q('correctionStatusCode')}, ${q('requestedAtUtc')})`,
    `CREATE TABLE IF NOT EXISTS ${q('AttendanceLogs')} (
      ${q('attendanceLogId')} bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ${q('attendanceRecordId')} bigint NOT NULL,
      ${q('attendanceCorrectionId')} bigint NULL,
      ${q('actionCode')} varchar(15) NOT NULL,
      ${q('oldCheckInAtUtc')} timestamptz(3) NULL,
      ${q('oldCheckOutAtUtc')} timestamptz(3) NULL,
      ${q('newCheckInAtUtc')} timestamptz(3) NULL,
      ${q('newCheckOutAtUtc')} timestamptz(3) NULL,
      ${q('oldIsExcused')} boolean NULL,
      ${q('newIsExcused')} boolean NOT NULL DEFAULT false,
      ${q('oldExcuseReason')} varchar(500) NULL,
      ${q('newExcuseReason')} varchar(500) NULL,
      ${q('actorUserId')} integer NOT NULL,
      ${q('recordedAtUtc')} timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      ${q('deviceNote')} varchar(200) NULL,
      ${q('isCancelled')} boolean NOT NULL DEFAULT false,
      CONSTRAINT fk_attendance_logs_record FOREIGN KEY (${q('attendanceRecordId')})
        REFERENCES ${q('AttendanceRecords')} (${q('attendanceRecordId')}) ON DELETE CASCADE,
      CONSTRAINT fk_attendance_logs_correction FOREIGN KEY (
        ${q('attendanceRecordId')}, ${q('attendanceCorrectionId')}
      ) REFERENCES ${q('AttendanceCorrections')} (${q('attendanceRecordId')}, ${q('attendanceCorrectionId')}),
      CONSTRAINT fk_attendance_logs_actor FOREIGN KEY (${q('actorUserId')})
        REFERENCES ${q('Users')} (${q('userId')}),
      CONSTRAINT ck_attendance_logs_action CHECK (${q('actionCode')} IN ('CHECK_IN', 'CHECK_OUT', 'CORRECTION')),
      CONSTRAINT ck_attendance_logs_correction CHECK (
        (${q('actionCode')} = 'CORRECTION' AND ${q('attendanceCorrectionId')} IS NOT NULL)
        OR (${q('actionCode')} IN ('CHECK_IN', 'CHECK_OUT') AND ${q('attendanceCorrectionId')} IS NULL)
      )
    )`,
    `CREATE INDEX IF NOT EXISTS ix_attendance_logs_record
      ON ${q('AttendanceLogs')} (${q('attendanceRecordId')}, ${q('attendanceLogId')})`,
    `CREATE INDEX IF NOT EXISTS ix_attendance_logs_lookup
      ON ${q('AttendanceLogs')} (${q('recordedAtUtc')})`,
    `CREATE OR REPLACE VIEW ${q('AttendanceSessionStatus')} AS
     SELECT
       r.${q('attendanceRecordId')},
       ep.${q('eventSessionId')},
       ep.${q('studentId')},
       ep.${q('studentEnrollmentId')},
       r.${q('checkedInAtUtc')},
       r.${q('checkedOutAtUtc')},
       r.${q('isExcused')},
       r.${q('excuseReason')},
       CASE
         WHEN r.${q('isExcused')} THEN 'EXCUSED'
         WHEN r.${q('checkedInAtUtc')} IS NULL THEN 'ABSENT'
         WHEN r.${q('checkedInAtUtc')} > es.${q('lateAfterUtc')} THEN 'LATE'
         ELSE 'PRESENT'
       END AS ${q('attendanceStatusCode')},
       CASE
         WHEN r.${q('checkedInAtUtc')} IS NOT NULL AND r.${q('checkedOutAtUtc')} IS NOT NULL
           THEN floor(extract(epoch FROM (r.${q('checkedOutAtUtc')} - r.${q('checkedInAtUtc')})) / 60)::int
         ELSE NULL
       END AS ${q('minutesPresent')}
     FROM ${q('AttendanceRecords')} r
     JOIN ${q('EventParticipants')} ep ON ep.${q('eventParticipantId')} = r.${q('eventParticipantId')}
     JOIN ${q('EventSessions')} es ON es.${q('eventSessionId')} = ep.${q('eventSessionId')}`,
  ];
}

type Queryable = {
  query: (text: string, values?: unknown[]) => Promise<{ rows: Record<string, unknown>[]; rowCount: number | null }>;
};

async function relationExists(db: Queryable, name: string): Promise<boolean> {
  const res = await db.query('SELECT to_regclass($1) AS rel', [name]);
  return res.rows[0]?.rel != null;
}

async function columnExists(db: Queryable, table: string, column: string): Promise<boolean> {
  const res = await db.query(
    `SELECT 1 FROM information_schema.columns
     WHERE table_schema = current_schema() AND table_name = $1 AND column_name = $2`,
    [table, column],
  );
  return (res.rowCount ?? 0) > 0;
}

async function ignoreDuplicate(db: Queryable, sql: string): Promise<void> {
  try {
    await db.query(sql);
  } catch (e: unknown) {
    const code = e && typeof e === 'object' && 'code' in e ? String((e as { code: unknown }).code) : '';
    if (code === '42710' || code === '42P07') return;
    throw e;
  }
}

const SNAKE_TABLES_TO_PASCAL: [string, string][] = [
  ['users', 'Users'],
  ['academic_years', 'AcademicYears'],
  ['academic_terms', 'AcademicTerms'],
  ['academic_programs', 'AcademicPrograms'],
  ['sections', 'Sections'],
  ['students', 'Students'],
  ['student_enrollments', 'StudentEnrollments'],
  ['events', 'Events'],
  ['event_sessions', 'EventSessions'],
  ['event_participants', 'EventParticipants'],
  ['attendance_records', 'AttendanceRecords'],
  ['attendance_corrections', 'AttendanceCorrections'],
  ['attendance_logs', 'AttendanceLogs'],
];

const SNAKE_COLUMNS_TO_CAMEL: [string, string][] = [
  ['academic_program_id', 'academicProgramId'],
  ['academic_term_id', 'academicTermId'],
  ['academic_year_id', 'academicYearId'],
  ['action_code', 'actionCode'],
  ['actor_user_id', 'actorUserId'],
  ['added_at_utc', 'addedAtUtc'],
  ['added_by_user_id', 'addedByUserId'],
  ['attendance_correction_id', 'attendanceCorrectionId'],
  ['attendance_log_id', 'attendanceLogId'],
  ['attendance_record_id', 'attendanceRecordId'],
  ['attendance_status_code', 'attendanceStatusCode'],
  ['check_in_closes_at_utc', 'checkInClosesAtUtc'],
  ['check_in_opens_at_utc', 'checkInOpensAtUtc'],
  ['check_out_closes_at_utc', 'checkOutClosesAtUtc'],
  ['check_out_opens_at_utc', 'checkOutOpensAtUtc'],
  ['checked_in_at_utc', 'checkedInAtUtc'],
  ['checked_out_at_utc', 'checkedOutAtUtc'],
  ['correction_status_code', 'correctionStatusCode'],
  ['created_at_utc', 'createdAtUtc'],
  ['created_by_user_id', 'createdByUserId'],
  ['device_note', 'deviceNote'],
  ['display_name', 'displayName'],
  ['effective_from_utc', 'effectiveFromUtc'],
  ['effective_to_utc', 'effectiveToUtc'],
  ['ends_at_utc', 'endsAtUtc'],
  ['ends_on', 'endsOn'],
  ['enrollment_status_code', 'enrollmentStatusCode'],
  ['event_code', 'eventCode'],
  ['event_date', 'eventDate'],
  ['event_id', 'eventId'],
  ['event_name', 'eventName'],
  ['event_participant_id', 'eventParticipantId'],
  ['event_session_id', 'eventSessionId'],
  ['event_status_code', 'eventStatusCode'],
  ['excuse_reason', 'excuseReason'],
  ['expected_row_version', 'expectedRowVersion'],
  ['first_name', 'firstName'],
  ['is_active', 'isActive'],
  ['is_cancelled', 'isCancelled'],
  ['is_closed', 'isClosed'],
  ['is_excused', 'isExcused'],
  ['is_required', 'isRequired'],
  ['last_changed_at_utc', 'lastChangedAtUtc'],
  ['last_changed_by_user_id', 'lastChangedByUserId'],
  ['last_name', 'lastName'],
  ['late_after_utc', 'lateAfterUtc'],
  ['middle_name', 'middleName'],
  ['minimum_minutes', 'minimumMinutes'],
  ['minutes_present', 'minutesPresent'],
  ['new_check_in_at_utc', 'newCheckInAtUtc'],
  ['new_check_out_at_utc', 'newCheckOutAtUtc'],
  ['new_excuse_reason', 'newExcuseReason'],
  ['new_is_excused', 'newIsExcused'],
  ['old_check_in_at_utc', 'oldCheckInAtUtc'],
  ['old_check_out_at_utc', 'oldCheckOutAtUtc'],
  ['old_excuse_reason', 'oldExcuseReason'],
  ['old_is_excused', 'oldIsExcused'],
  ['password_hash', 'passwordHash'],
  ['photo_url', 'photoUrl'],
  ['program_code', 'programCode'],
  ['program_name', 'programName'],
  ['proposed_check_in_at_utc', 'proposedCheckInAtUtc'],
  ['proposed_check_out_at_utc', 'proposedCheckOutAtUtc'],
  ['proposed_excuse_reason', 'proposedExcuseReason'],
  ['proposed_is_excused', 'proposedIsExcused'],
  ['recorded_at_utc', 'recordedAtUtc'],
  ['requested_at_utc', 'requestedAtUtc'],
  ['requested_by_user_id', 'requestedByUserId'],
  ['requires_check_out', 'requiresCheckOut'],
  ['review_note', 'reviewNote'],
  ['reviewed_at_utc', 'reviewedAtUtc'],
  ['reviewed_by_user_id', 'reviewedByUserId'],
  ['row_version', 'rowVersion'],
  ['section_code', 'sectionCode'],
  ['section_id', 'sectionId'],
  ['section_name', 'sectionName'],
  ['session_code', 'sessionCode'],
  ['session_name', 'sessionName'],
  ['sort_order', 'sortOrder'],
  ['starts_at_utc', 'startsAtUtc'],
  ['starts_on', 'startsOn'],
  ['student_enrollment_id', 'studentEnrollmentId'],
  ['student_id', 'studentId'],
  ['student_number', 'studentNumber'],
  ['term_code', 'termCode'],
  ['term_name', 'termName'],
  ['updated_at_utc', 'updatedAtUtc'],
  ['user_id', 'userId'],
  ['year_code', 'yearCode'],
  ['year_level', 'yearLevel'],
  ['year_name', 'yearName'],
];

/** Rename snake_case tables/columns to quoted PascalCase / camelCase. */
export async function renameSnakeToPascal(db: Queryable): Promise<void> {
  if (await relationExists(db, q('Users'))) return;
  if (!(await relationExists(db, 'users'))) return;

  await db.query('DROP VIEW IF EXISTS v_attendance_session_status');
  await db.query(`DROP VIEW IF EXISTS ${q('AttendanceSessionStatus')}`);

  for (const [from, to] of SNAKE_TABLES_TO_PASCAL) {
    if (await relationExists(db, from)) {
      await db.query(`ALTER TABLE ${from} RENAME TO ${q(to)}`);
    }
  }

  for (const [, table] of SNAKE_TABLES_TO_PASCAL) {
    if (!(await relationExists(db, q(table)))) continue;
    for (const [from, to] of SNAKE_COLUMNS_TO_CAMEL) {
      if (await columnExists(db, table, from)) {
        await db.query(`ALTER TABLE ${q(table)} RENAME COLUMN ${from} TO ${q(to)}`);
      }
    }
  }
}

/** Strip the previous multi-tenant columns/tables from an already-installed schema. */
export async function dropTenantsIfPresent(db: Queryable): Promise<void> {
  const hasTenants = await relationExists(db, 'tenants');
  const hasTenantCol = await columnExists(db, 'students', 'tenant_id');
  if (!hasTenants && !hasTenantCol) return;

  await db.query('DROP VIEW IF EXISTS v_attendance_session_status');

  if (await relationExists(db, 'user_tenants')) {
    await db.query('ALTER TABLE users ADD COLUMN IF NOT EXISTS role varchar(20)');
    await db.query(
      `UPDATE users u
       SET role = ut.role_code
       FROM user_tenants ut
       WHERE ut.user_id = u.user_id AND (u.role IS NULL OR u.role = '')`,
    );
  }
  if (await columnExists(db, 'users', 'role')) {
    await db.query(`UPDATE users SET role = 'moderator' WHERE role IS NULL`);
    await db.query('ALTER TABLE users ALTER COLUMN role SET NOT NULL');
  }

  const tables = [
    'attendance_logs',
    'attendance_corrections',
    'attendance_records',
    'event_participants',
    'event_sessions',
    'events',
    'student_enrollments',
    'students',
    'sections',
    'academic_programs',
    'academic_terms',
    'academic_years',
  ];
  for (const table of tables) {
    if ((await relationExists(db, table)) && (await columnExists(db, table, 'tenant_id'))) {
      await db.query(`ALTER TABLE ${table} DROP COLUMN tenant_id CASCADE`);
    }
  }

  await db.query('DROP TABLE IF EXISTS user_tenants CASCADE');
  await db.query('DROP TABLE IF EXISTS tenants CASCADE');
}

/** Recreate unique/FK constraints dropped with tenant_id. Safe on a fresh install. */
export async function addMissingConstraints(db: Queryable): Promise<void> {
  if (!(await relationExists(db, q('Users')))) return;

  if (await columnExists(db, 'Users', 'role')) {
    await ignoreDuplicate(
      db,
      `ALTER TABLE ${q('Users')} ADD CONSTRAINT ck_users_role CHECK (role IN ('superadmin', 'moderator', 'student'))`,
    );
  }
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('AcademicYears')} ADD CONSTRAINT uq_academic_years_code UNIQUE (${q('yearCode')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('AcademicTerms')} ADD CONSTRAINT uq_academic_terms_code UNIQUE (${q('academicYearId')}, ${q('termCode')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('AcademicTerms')} ADD CONSTRAINT fk_academic_terms_year
     FOREIGN KEY (${q('academicYearId')}) REFERENCES ${q('AcademicYears')} (${q('academicYearId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('AcademicPrograms')} ADD CONSTRAINT uq_academic_programs_code UNIQUE (${q('programCode')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('Sections')} ADD CONSTRAINT uq_sections_context
     UNIQUE (${q('academicTermId')}, ${q('academicProgramId')}, ${q('yearLevel')}, ${q('sectionId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('Sections')} ADD CONSTRAINT uq_sections_code
     UNIQUE (${q('academicTermId')}, ${q('academicProgramId')}, ${q('sectionCode')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('Sections')} ADD CONSTRAINT fk_sections_term
     FOREIGN KEY (${q('academicTermId')}) REFERENCES ${q('AcademicTerms')} (${q('academicTermId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('Sections')} ADD CONSTRAINT fk_sections_program
     FOREIGN KEY (${q('academicProgramId')}) REFERENCES ${q('AcademicPrograms')} (${q('academicProgramId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('Students')} ADD CONSTRAINT uq_students_number UNIQUE (${q('studentNumber')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('Students')} ADD CONSTRAINT fk_students_user FOREIGN KEY (${q('userId')}) REFERENCES ${q('Users')} (${q('userId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('StudentEnrollments')} ADD CONSTRAINT uq_student_enrollments_context
     UNIQUE (${q('academicTermId')}, ${q('studentEnrollmentId')}, ${q('studentId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('StudentEnrollments')} ADD CONSTRAINT fk_student_enrollments_student
     FOREIGN KEY (${q('studentId')}) REFERENCES ${q('Students')} (${q('studentId')}) ON DELETE CASCADE`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('StudentEnrollments')} ADD CONSTRAINT fk_student_enrollments_term
     FOREIGN KEY (${q('academicTermId')}) REFERENCES ${q('AcademicTerms')} (${q('academicTermId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('StudentEnrollments')} ADD CONSTRAINT fk_student_enrollments_program
     FOREIGN KEY (${q('academicProgramId')}) REFERENCES ${q('AcademicPrograms')} (${q('academicProgramId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('StudentEnrollments')} ADD CONSTRAINT fk_student_enrollments_section
     FOREIGN KEY (${q('academicTermId')}, ${q('academicProgramId')}, ${q('yearLevel')}, ${q('sectionId')})
     REFERENCES ${q('Sections')} (${q('academicTermId')}, ${q('academicProgramId')}, ${q('yearLevel')}, ${q('sectionId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('Events')} ADD CONSTRAINT uq_events_context UNIQUE (${q('eventId')}, ${q('academicTermId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('Events')} ADD CONSTRAINT uq_events_code UNIQUE (${q('eventCode')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('Events')} ADD CONSTRAINT fk_events_term
     FOREIGN KEY (${q('academicTermId')}) REFERENCES ${q('AcademicTerms')} (${q('academicTermId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('Events')} ADD CONSTRAINT fk_events_creator
     FOREIGN KEY (${q('createdByUserId')}) REFERENCES ${q('Users')} (${q('userId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('EventSessions')} ADD CONSTRAINT uq_event_sessions_context
     UNIQUE (${q('eventSessionId')}, ${q('academicTermId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('EventSessions')} ADD CONSTRAINT uq_event_sessions_code UNIQUE (${q('eventId')}, ${q('sessionCode')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('EventSessions')} ADD CONSTRAINT fk_event_sessions_event
     FOREIGN KEY (${q('eventId')}, ${q('academicTermId')}) REFERENCES ${q('Events')} (${q('eventId')}, ${q('academicTermId')}) ON DELETE CASCADE`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('EventParticipants')} ADD CONSTRAINT uq_event_participants_student_session
     UNIQUE (${q('eventSessionId')}, ${q('studentId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('EventParticipants')} ADD CONSTRAINT fk_event_participants_session
     FOREIGN KEY (${q('eventSessionId')}, ${q('academicTermId')})
     REFERENCES ${q('EventSessions')} (${q('eventSessionId')}, ${q('academicTermId')}) ON DELETE CASCADE`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('EventParticipants')} ADD CONSTRAINT fk_event_participants_enrollment
     FOREIGN KEY (${q('academicTermId')}, ${q('studentEnrollmentId')}, ${q('studentId')})
     REFERENCES ${q('StudentEnrollments')} (${q('academicTermId')}, ${q('studentEnrollmentId')}, ${q('studentId')}) ON DELETE CASCADE`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('EventParticipants')} ADD CONSTRAINT fk_event_participants_actor
     FOREIGN KEY (${q('addedByUserId')}) REFERENCES ${q('Users')} (${q('userId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('AttendanceRecords')} ADD CONSTRAINT uq_attendance_records_participant UNIQUE (${q('eventParticipantId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('AttendanceRecords')} ADD CONSTRAINT fk_attendance_records_participant
     FOREIGN KEY (${q('eventParticipantId')}) REFERENCES ${q('EventParticipants')} (${q('eventParticipantId')}) ON DELETE CASCADE`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('AttendanceRecords')} ADD CONSTRAINT fk_attendance_records_actor
     FOREIGN KEY (${q('lastChangedByUserId')}) REFERENCES ${q('Users')} (${q('userId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('AttendanceCorrections')} ADD CONSTRAINT uq_attendance_corrections_context
     UNIQUE (${q('attendanceRecordId')}, ${q('attendanceCorrectionId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('AttendanceCorrections')} ADD CONSTRAINT fk_attendance_corrections_record
     FOREIGN KEY (${q('attendanceRecordId')}) REFERENCES ${q('AttendanceRecords')} (${q('attendanceRecordId')}) ON DELETE CASCADE`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('AttendanceCorrections')} ADD CONSTRAINT fk_attendance_corrections_requester
     FOREIGN KEY (${q('requestedByUserId')}) REFERENCES ${q('Users')} (${q('userId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('AttendanceCorrections')} ADD CONSTRAINT fk_attendance_corrections_reviewer
     FOREIGN KEY (${q('reviewedByUserId')}) REFERENCES ${q('Users')} (${q('userId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('AttendanceLogs')} ADD CONSTRAINT fk_attendance_logs_record
     FOREIGN KEY (${q('attendanceRecordId')}) REFERENCES ${q('AttendanceRecords')} (${q('attendanceRecordId')}) ON DELETE CASCADE`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('AttendanceLogs')} ADD CONSTRAINT fk_attendance_logs_correction
     FOREIGN KEY (${q('attendanceRecordId')}, ${q('attendanceCorrectionId')})
     REFERENCES ${q('AttendanceCorrections')} (${q('attendanceRecordId')}, ${q('attendanceCorrectionId')})`,
  );
  await ignoreDuplicate(
    db,
    `ALTER TABLE ${q('AttendanceLogs')} ADD CONSTRAINT fk_attendance_logs_actor
     FOREIGN KEY (${q('actorUserId')}) REFERENCES ${q('Users')} (${q('userId')})`,
  );
}

/** Rename the previous 5-table attendance schema so the new tables can be created. */
export async function migrateLegacyTables(db: Queryable): Promise<boolean> {
  const isLegacy =
    (await relationExists(db, 'session_windows')) && (await columnExists(db, 'students', 'student_id_code'));
  if (!isLegacy) return false;

  await db.query('ALTER TABLE IF EXISTS attendance_logs RENAME TO _legacy_attendance_logs');
  await db.query('ALTER TABLE IF EXISTS session_windows RENAME TO _legacy_session_windows');
  await db.query('ALTER TABLE IF EXISTS events RENAME TO _legacy_events');
  await db.query('ALTER TABLE IF EXISTS students RENAME TO _legacy_students');
  await db.query('ALTER TABLE IF EXISTS users RENAME TO _legacy_users');
  return true;
}

export async function seedFoundation(db: Queryable): Promise<void> {
  await db.query(
    `INSERT INTO ${q('AcademicYears')} (
        ${q('yearCode')}, ${q('yearName')}, ${q('startsOn')}, ${q('endsOn')}, ${q('isActive')}
     )
     VALUES
       ('DEFAULT', 'Default Academic Year', DATE '2020-01-01', DATE '2039-12-31', true),
       ('2025-2026', 'Academic Year 2025–2026', DATE '2025-08-01', DATE '2026-07-31', false),
       ('2026-2027', 'Academic Year 2026–2027', DATE '2026-08-01', DATE '2027-07-31', true)
     ON CONFLICT (${q('yearCode')}) DO NOTHING`,
  );
  await db.query(
    `INSERT INTO ${q('AcademicTerms')} (
        ${q('academicYearId')}, ${q('termCode')}, ${q('termName')},
        ${q('startsOn')}, ${q('endsOn')}, ${q('isActive')}
     )
     SELECT y.${q('academicYearId')}, v.term_code, v.term_name, v.starts_on, v.ends_on, v.is_active
     FROM (
       VALUES
         ('DEFAULT', 'DEFAULT', 'Default Term', DATE '2020-01-01', DATE '2039-12-31', true),
         ('2025-2026', '2025-1S', 'First Semester', DATE '2025-08-04', DATE '2025-12-19', false),
         ('2025-2026', '2025-2S', 'Second Semester', DATE '2026-01-05', DATE '2026-05-15', false),
         ('2025-2026', '2025-MID', 'Midyear', DATE '2026-06-01', DATE '2026-07-24', false),
         ('2026-2027', '2026-1S', 'First Semester', DATE '2026-08-03', DATE '2026-12-18', true),
         ('2026-2027', '2026-2S', 'Second Semester', DATE '2027-01-05', DATE '2027-05-14', false),
         ('2026-2027', '2026-MID', 'Midyear', DATE '2027-06-01', DATE '2027-07-23', false)
     ) AS v(year_code, term_code, term_name, starts_on, ends_on, is_active)
     JOIN ${q('AcademicYears')} y ON y.${q('yearCode')} = v.year_code
     ON CONFLICT (${q('academicYearId')}, ${q('termCode')}) DO NOTHING`,
  );
  await db.query(
    `INSERT INTO ${q('AcademicPrograms')} (${q('programCode')}, ${q('programName')})
     VALUES
       ('GEN', 'General'),
       ('BSIT', 'Bachelor of Science in Information Technology'),
       ('BSCS', 'Bachelor of Science in Computer Science'),
       ('BSCPE', 'Bachelor of Science in Computer Engineering'),
       ('BSIS', 'Bachelor of Science in Information Systems'),
       ('ACT', 'Associate in Computer Technology'),
       ('BSBA', 'Bachelor of Science in Business Administration'),
       ('BSHM', 'Bachelor of Science in Hospitality Management'),
       ('BSTM', 'Bachelor of Science in Tourism Management')
     ON CONFLICT (${q('programCode')}) DO NOTHING`,
  );
}

export async function importLegacyData(db: Queryable): Promise<void> {
  if (!(await relationExists(db, '_legacy_users'))) return;

  await db.query(
    `INSERT INTO ${q('Users')} (${q('userId')}, username, ${q('passwordHash')}, ${q('displayName')}, role, ${q('createdAtUtc')}, ${q('updatedAtUtc')})
     OVERRIDING SYSTEM VALUE
     SELECT id, username, password_hash, name,
            CASE WHEN role IN ('superadmin', 'moderator', 'student') THEN role ELSE 'moderator' END,
            created_at, updated_at
     FROM _legacy_users`,
  );
  await db.query(
    `SELECT setval(pg_get_serial_sequence('${q('Users')}', 'userId'), COALESCE((SELECT MAX(${q('userId')}) FROM ${q('Users')}), 1), true)`,
  );

  await db.query(
    `INSERT INTO ${q('Students')} (
        ${q('studentId')}, ${q('studentNumber')}, ${q('firstName')}, ${q('lastName')}, ${q('middleName')},
        ${q('photoUrl')}, ${q('createdAtUtc')}, ${q('updatedAtUtc')}
     )
     OVERRIDING SYSTEM VALUE
     SELECT
       s.id,
       s.student_id_code,
       COALESCE(NULLIF(split_part(btrim(s.full_name), ' ', 1), ''), s.full_name),
       CASE
         WHEN position(' ' IN btrim(s.full_name)) = 0 THEN btrim(s.full_name)
         ELSE regexp_replace(btrim(s.full_name), '^\\S+\\s+', '')
       END,
       NULL,
       s.photo_url,
       s.created_at,
       s.updated_at
     FROM _legacy_students s`,
  );
  await db.query(
    `SELECT setval(pg_get_serial_sequence('${q('Students')}', 'studentId'), COALESCE((SELECT MAX(${q('studentId')}) FROM ${q('Students')}), 1), true)`,
  );

  await db.query(
    `INSERT INTO ${q('StudentEnrollments')} (
        ${q('studentId')}, ${q('academicTermId')}, ${q('academicProgramId')}, ${q('sectionId')},
        ${q('yearLevel')}, ${q('enrollmentStatusCode')}, ${q('effectiveFromUtc')}
     )
     SELECT s.${q('studentId')}, term.${q('academicTermId')}, p.${q('academicProgramId')}, NULL,
            1, 'ENROLLED', clock_timestamp()
     FROM ${q('Students')} s
     JOIN ${q('AcademicTerms')} term ON term.${q('termCode')} = 'DEFAULT'
     JOIN ${q('AcademicPrograms')} p ON p.${q('programCode')} = 'GEN'`,
  );

  await db.query(
    `INSERT INTO ${q('Events')} (
        ${q('eventId')}, ${q('academicTermId')}, ${q('eventCode')}, ${q('eventName')}, ${q('eventDate')},
        ${q('eventStatusCode')}, ${q('createdByUserId')}, ${q('createdAtUtc')}, ${q('updatedAtUtc')}
     )
     OVERRIDING SYSTEM VALUE
     SELECT
       e.id,
       term.${q('academicTermId')},
       'EVT-' || e.id::text,
       e.name,
       e.event_date::date,
       CASE WHEN e.is_active THEN 'PUBLISHED' ELSE 'CLOSED' END,
       e.created_by,
       e.created_at,
       e.updated_at
     FROM _legacy_events e
     JOIN ${q('AcademicTerms')} term ON term.${q('termCode')} = 'DEFAULT'`,
  );
  await db.query(
    `SELECT setval(pg_get_serial_sequence('${q('Events')}', 'eventId'), COALESCE((SELECT MAX(${q('eventId')}) FROM ${q('Events')}), 1), true)`,
  );

  await db.query(
    `INSERT INTO ${q('EventSessions')} (
        ${q('eventSessionId')}, ${q('eventId')}, ${q('academicTermId')}, ${q('sessionCode')}, ${q('sessionName')},
        ${q('startsAtUtc')}, ${q('endsAtUtc')}, ${q('checkInOpensAtUtc')}, ${q('checkInClosesAtUtc')}, ${q('lateAfterUtc')},
        ${q('checkOutOpensAtUtc')}, ${q('checkOutClosesAtUtc')}, ${q('sortOrder')}
     )
     OVERRIDING SYSTEM VALUE
     SELECT
       w.id,
       w.event_id,
       ev.${q('academicTermId')},
       'S' || w.id::text,
       w.session_label,
       (ev.${q('eventDate')}::timestamp + w.start_time::time),
       (ev.${q('eventDate')}::timestamp + w.end_time::time),
       (ev.${q('eventDate')}::timestamp + w.start_time::time),
       (ev.${q('eventDate')}::timestamp + w.end_time::time),
       (ev.${q('eventDate')}::timestamp + w.start_time::time),
       (ev.${q('eventDate')}::timestamp + w.start_time::time),
       (ev.${q('eventDate')}::timestamp + w.end_time::time),
       w.sort_order
     FROM _legacy_session_windows w
     JOIN ${q('Events')} ev ON ev.${q('eventId')} = w.event_id`,
  );
  await db.query(
    `SELECT setval(pg_get_serial_sequence('${q('EventSessions')}', 'eventSessionId'), COALESCE((SELECT MAX(${q('eventSessionId')}) FROM ${q('EventSessions')}), 1), true)`,
  );

  if (await relationExists(db, '_legacy_attendance_logs')) {
    await db.query(
      `INSERT INTO ${q('EventParticipants')} (
          ${q('eventSessionId')}, ${q('academicTermId')}, ${q('studentEnrollmentId')},
          ${q('studentId')}, ${q('addedByUserId')}
       )
       SELECT DISTINCT ON (l.session_window_id, l.student_id)
         l.session_window_id, se.${q('academicTermId')}, se.${q('studentEnrollmentId')},
         l.student_id, l.scanned_by
       FROM _legacy_attendance_logs l
       JOIN ${q('StudentEnrollments')} se
         ON se.${q('studentId')} = l.student_id AND se.${q('effectiveToUtc')} IS NULL`,
    );
    await db.query(
      `INSERT INTO ${q('AttendanceRecords')} (${q('eventParticipantId')}, ${q('lastChangedByUserId')})
       SELECT ep.${q('eventParticipantId')}, ep.${q('addedByUserId')}
       FROM ${q('EventParticipants')} ep
       ON CONFLICT (${q('eventParticipantId')}) DO NOTHING`,
    );
    await db.query(
      `INSERT INTO ${q('AttendanceLogs')} (
          ${q('attendanceRecordId')}, ${q('actionCode')},
          ${q('newCheckInAtUtc')}, ${q('newCheckOutAtUtc')}, ${q('newIsExcused')},
          ${q('actorUserId')}, ${q('recordedAtUtc')}, ${q('deviceNote')}, ${q('isCancelled')}
       )
       SELECT
         ar.${q('attendanceRecordId')},
         CASE WHEN l.direction = 'OUT' THEN 'CHECK_OUT' ELSE 'CHECK_IN' END,
         CASE WHEN l.direction = 'OUT' THEN NULL ELSE l.scanned_at END,
         CASE WHEN l.direction = 'OUT' THEN l.scanned_at ELSE NULL END,
         false,
         l.scanned_by,
         l.scanned_at,
         l.device_note,
         COALESCE(l.status = 'cancelled', false)
       FROM _legacy_attendance_logs l
       JOIN ${q('EventParticipants')} ep
         ON ep.${q('eventSessionId')} = l.session_window_id AND ep.${q('studentId')} = l.student_id
       JOIN ${q('AttendanceRecords')} ar
         ON ar.${q('eventParticipantId')} = ep.${q('eventParticipantId')}`,
    );
    await db.query(
      `UPDATE ${q('AttendanceRecords')} ar
       SET ${q('checkedInAtUtc')} = sub.cin,
           ${q('checkedOutAtUtc')} = CASE WHEN sub.cin IS NULL THEN NULL ELSE sub.cout END,
           ${q('lastChangedAtUtc')} = clock_timestamp()
       FROM (
         SELECT
           ${q('attendanceRecordId')},
           MIN(${q('recordedAtUtc')}) FILTER (WHERE ${q('actionCode')} = 'CHECK_IN' AND NOT ${q('isCancelled')}) AS cin,
           MIN(${q('recordedAtUtc')}) FILTER (WHERE ${q('actionCode')} = 'CHECK_OUT' AND NOT ${q('isCancelled')}) AS cout
         FROM ${q('AttendanceLogs')}
         GROUP BY ${q('attendanceRecordId')}
       ) sub
       WHERE ar.${q('attendanceRecordId')} = sub.${q('attendanceRecordId')}`,
    );
  }

  await db.query(`DROP TABLE IF EXISTS _legacy_attendance_logs CASCADE`);
  await db.query(`DROP TABLE IF EXISTS _legacy_session_windows CASCADE`);
  await db.query(`DROP TABLE IF EXISTS _legacy_events CASCADE`);
  await db.query(`DROP TABLE IF EXISTS _legacy_students CASCADE`);
  await db.query(`DROP TABLE IF EXISTS _legacy_users CASCADE`);
}
