function assertIdent(name: string): string {
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name)) {
    throw new Error(`Invalid SQL identifier: ${name}`);
  }
  return name;
}

export function schemaStatements(schema = 'ssc'): string[] {
  const s = assertIdent(schema);
  return [
    `CREATE SCHEMA IF NOT EXISTS ${s}`,
    `SET search_path TO ${s}`,
    `CREATE TABLE IF NOT EXISTS users (
      id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name            TEXT NOT NULL,
      username        TEXT NOT NULL UNIQUE,
      password_hash   TEXT NOT NULL,
      role            TEXT NOT NULL,
      created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`,
    `CREATE TABLE IF NOT EXISTS students (
      id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      student_id_code   TEXT NOT NULL UNIQUE,
      full_name         TEXT NOT NULL,
      section           TEXT,
      photo_url         TEXT,
      created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`,
    `CREATE TABLE IF NOT EXISTS events (
      id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name        TEXT NOT NULL,
      event_date  TIMESTAMPTZ NOT NULL,
      is_active   BOOLEAN NOT NULL DEFAULT TRUE,
      created_by  INTEGER NOT NULL REFERENCES users(id),
      created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`,
    `CREATE TABLE IF NOT EXISTS session_windows (
      id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      event_id       INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
      session_label  TEXT NOT NULL,
      start_time     TEXT NOT NULL,
      end_time       TEXT NOT NULL,
      sort_order     INTEGER NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS attendance_logs (
      id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      event_id            INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
      student_id          INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
      session_window_id   INTEGER NOT NULL REFERENCES session_windows(id) ON DELETE CASCADE,
      direction           TEXT NOT NULL,
      scanned_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      scanned_by          INTEGER NOT NULL REFERENCES users(id),
      status              TEXT NOT NULL,
      device_note         TEXT,
      updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`,
    `CREATE INDEX IF NOT EXISTS idx_attendance_lookup
      ON attendance_logs (event_id, student_id, session_window_id, status)`,
  ];
}
