include: package:dart_frog_lint/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - build/**

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    no_default_cases: false
    avoid_print: false
    cascade_invocations: false
    always_use_package_imports: false
    prefer_constructors_over_static_methods: false
    use_setters_to_change_properties: false
    sort_constructors_first: false
    avoid_redundant_argument_values: false
    combinators_ordering: false
    matching_super_parameters: false
    prefer_const_declarations: false
    curly_braces_in_flow_control_structures: false
