/*
SSC Attendance — PostgreSQL schema for database [aclc], schema ssc

Single-school install (no tenants table). Role lives on "Users".

  Database: aclc
  Schema:   ssc

Quoted identifiers: PascalCase tables, camelCase columns.
REST JSON / Flutter field names stay snake_case.

External sign-in:
  "AuthProviders" lookup (google, microsoft, apple)
  "ExternalLogins" links a "Users" row to one IdP subject

App-needed extra columns:
  "Users"."passwordHash", "Users".role, "Users"."updatedAtUtc"
  "Students"."photoUrl", "Students"."updatedAtUtc"
  "Events"."eventDate", "Events"."updatedAtUtc"
  "EventSessions"."sortOrder"
  "AttendanceLogs"."deviceNote", "AttendanceLogs"."isCancelled"

Connect to database aclc before running. The Node server applies the same
definitions via server/src/db/schema.ts (preferred).
*/

CREATE SCHEMA IF NOT EXISTS ssc;

SET search_path TO ssc;

CREATE OR REPLACE FUNCTION new_row_version()
     RETURNS bytea
     LANGUAGE sql
     AS $$
       SELECT decode(substr(md5(random()::text || clock_timestamp()::text), 1, 16), 'hex')
     $$;

CREATE OR REPLACE FUNCTION bump_row_version()
     RETURNS trigger
     LANGUAGE plpgsql
     AS $$
     BEGIN
       NEW."rowVersion" := new_row_version();
       RETURN NEW;
     END;
     $$;

DROP VIEW IF EXISTS v_attendance_session_status;

CREATE TABLE IF NOT EXISTS "Users" (
      "userId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username varchar(100) NOT NULL,
      "passwordHash" text NOT NULL,
      "displayName" varchar(200) NOT NULL,
      role varchar(20) NOT NULL,
      "isActive" boolean NOT NULL DEFAULT true,
      "createdAtUtc" timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      "updatedAtUtc" timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      "rowVersion" bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_users_username UNIQUE (username),
      CONSTRAINT ck_users_username CHECK (char_length(btrim(username)) > 0),
      CONSTRAINT ck_users_name CHECK (char_length(btrim("displayName")) > 0),
      CONSTRAINT ck_users_role CHECK (role IN ('superadmin', 'moderator', 'student'))
    );

CREATE TABLE IF NOT EXISTS "AuthProviders" (
      "authProviderId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "providerCode" varchar(30) NOT NULL,
      "displayName" varchar(100) NOT NULL,
      "isActive" boolean NOT NULL DEFAULT true,
      "createdAtUtc" timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      "rowVersion" bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_auth_providers_code UNIQUE ("providerCode"),
      CONSTRAINT ck_auth_providers_code CHECK (char_length(btrim("providerCode")) > 0),
      CONSTRAINT ck_auth_providers_name CHECK (char_length(btrim("displayName")) > 0)
    );

CREATE TABLE IF NOT EXISTS "ExternalLogins" (
      "externalLoginId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "userId" integer NOT NULL,
      "authProviderId" integer NOT NULL,
      "providerKey" varchar(255) NOT NULL,
      email varchar(320) NULL,
      "displayName" varchar(200) NULL,
      "linkedAtUtc" timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      "lastUsedAtUtc" timestamptz(3) NULL,
      "rowVersion" bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_external_logins_provider_key UNIQUE ("authProviderId", "providerKey"),
      CONSTRAINT uq_external_logins_user_provider UNIQUE ("userId", "authProviderId"),
      CONSTRAINT fk_external_logins_user FOREIGN KEY ("userId")
        REFERENCES "Users" ("userId") ON DELETE CASCADE,
      CONSTRAINT fk_external_logins_provider FOREIGN KEY ("authProviderId")
        REFERENCES "AuthProviders" ("authProviderId"),
      CONSTRAINT ck_external_logins_key CHECK (char_length(btrim("providerKey")) > 0)
    );

CREATE TABLE IF NOT EXISTS "AcademicYears" (
      "academicYearId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "yearCode" varchar(30) NOT NULL,
      "yearName" varchar(100) NOT NULL,
      "startsOn" date NOT NULL,
      "endsOn" date NOT NULL,
      "isActive" boolean NOT NULL DEFAULT true,
      "createdAtUtc" timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      "rowVersion" bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_academic_years_code UNIQUE ("yearCode"),
      CONSTRAINT ck_academic_years_dates CHECK ("startsOn" <= "endsOn")
    );

CREATE TABLE IF NOT EXISTS "AcademicTerms" (
      "academicTermId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "academicYearId" bigint NOT NULL,
      "termCode" varchar(30) NOT NULL,
      "termName" varchar(100) NOT NULL,
      "startsOn" date NOT NULL,
      "endsOn" date NOT NULL,
      "isActive" boolean NOT NULL DEFAULT true,
      "createdAtUtc" timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      "rowVersion" bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_academic_terms_code UNIQUE ("academicYearId", "termCode"),
      CONSTRAINT fk_academic_terms_year FOREIGN KEY ("academicYearId")
        REFERENCES "AcademicYears" ("academicYearId"),
      CONSTRAINT ck_academic_terms_dates CHECK ("startsOn" <= "endsOn")
    );

CREATE TABLE IF NOT EXISTS "AcademicPrograms" (
      "academicProgramId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "programCode" varchar(30) NOT NULL,
      "programName" varchar(200) NOT NULL,
      "isActive" boolean NOT NULL DEFAULT true,
      "createdAtUtc" timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      "rowVersion" bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_academic_programs_code UNIQUE ("programCode")
    );

CREATE TABLE IF NOT EXISTS "Sections" (
      "sectionId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "academicTermId" bigint NOT NULL,
      "academicProgramId" bigint NOT NULL,
      "yearLevel" smallint NOT NULL,
      "sectionCode" varchar(30) NOT NULL,
      "sectionName" varchar(100) NOT NULL,
      "isActive" boolean NOT NULL DEFAULT true,
      "createdAtUtc" timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      "rowVersion" bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_sections_context UNIQUE ("academicTermId", "academicProgramId", "yearLevel", "sectionId"),
      CONSTRAINT uq_sections_code UNIQUE ("academicTermId", "academicProgramId", "sectionCode"),
      CONSTRAINT fk_sections_term FOREIGN KEY ("academicTermId")
        REFERENCES "AcademicTerms" ("academicTermId"),
      CONSTRAINT fk_sections_program FOREIGN KEY ("academicProgramId")
        REFERENCES "AcademicPrograms" ("academicProgramId"),
      CONSTRAINT ck_sections_year_level CHECK ("yearLevel" BETWEEN 1 AND 20)
    );

CREATE TABLE IF NOT EXISTS "Students" (
      "studentId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "studentNumber" varchar(50) NOT NULL,
      "userId" integer NULL,
      "firstName" varchar(100) NOT NULL,
      "middleName" varchar(100) NULL,
      "lastName" varchar(100) NOT NULL,
      suffix varchar(30) NULL,
      "photoUrl" text NULL,
      "isActive" boolean NOT NULL DEFAULT true,
      "createdAtUtc" timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      "updatedAtUtc" timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      "rowVersion" bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_students_number UNIQUE ("studentNumber"),
      CONSTRAINT fk_students_user FOREIGN KEY ("userId") REFERENCES "Users" ("userId"),
      CONSTRAINT ck_students_number CHECK (char_length(btrim("studentNumber")) > 0),
      CONSTRAINT ck_students_name CHECK (
        char_length(btrim("firstName")) > 0 AND char_length(btrim("lastName")) > 0
      )
    );

CREATE UNIQUE INDEX IF NOT EXISTS ux_students_login
      ON "Students" ("userId")
      WHERE "userId" IS NOT NULL;

CREATE TABLE IF NOT EXISTS "StudentEnrollments" (
      "studentEnrollmentId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "studentId" bigint NOT NULL,
      "academicTermId" bigint NOT NULL,
      "academicProgramId" bigint NOT NULL,
      "sectionId" bigint NULL,
      "yearLevel" smallint NOT NULL,
      "enrollmentStatusCode" varchar(15) NOT NULL DEFAULT 'ENROLLED',
      "effectiveFromUtc" timestamptz(3) NOT NULL,
      "effectiveToUtc" timestamptz(3) NULL,
      "createdAtUtc" timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      "rowVersion" bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_student_enrollments_context UNIQUE (
        "academicTermId", "studentEnrollmentId", "studentId"
      ),
      CONSTRAINT fk_student_enrollments_student FOREIGN KEY ("studentId")
        REFERENCES "Students" ("studentId") ON DELETE CASCADE,
      CONSTRAINT fk_student_enrollments_term FOREIGN KEY ("academicTermId")
        REFERENCES "AcademicTerms" ("academicTermId"),
      CONSTRAINT fk_student_enrollments_program FOREIGN KEY ("academicProgramId")
        REFERENCES "AcademicPrograms" ("academicProgramId"),
      CONSTRAINT fk_student_enrollments_section FOREIGN KEY (
        "academicTermId", "academicProgramId", "yearLevel", "sectionId"
      ) REFERENCES "Sections" ("academicTermId", "academicProgramId", "yearLevel", "sectionId"),
      CONSTRAINT ck_student_enrollments_year CHECK ("yearLevel" BETWEEN 1 AND 20),
      CONSTRAINT ck_student_enrollments_status CHECK (
        "enrollmentStatusCode" IN ('ENROLLED', 'WITHDRAWN', 'COMPLETED', 'CANCELLED')
      ),
      CONSTRAINT ck_student_enrollments_dates CHECK (
        "effectiveToUtc" IS NULL OR "effectiveToUtc" > "effectiveFromUtc"
      )
    );

CREATE UNIQUE INDEX IF NOT EXISTS ux_student_enrollments_current
      ON "StudentEnrollments" ("studentId", "academicTermId")
      WHERE "effectiveToUtc" IS NULL;

CREATE INDEX IF NOT EXISTS ix_student_enrollments_roster
      ON "StudentEnrollments" ("academicTermId", "academicProgramId", "sectionId")
      INCLUDE ("studentId", "studentEnrollmentId", "enrollmentStatusCode", "effectiveFromUtc", "effectiveToUtc");

CREATE TABLE IF NOT EXISTS "Events" (
      "eventId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "academicTermId" bigint NOT NULL,
      "eventCode" varchar(50) NOT NULL,
      "eventName" varchar(200) NOT NULL,
      description varchar(2000) NULL,
      venue varchar(300) NULL,
      "eventDate" date NOT NULL,
      "eventStatusCode" varchar(12) NOT NULL DEFAULT 'DRAFT',
      "createdByUserId" integer NOT NULL,
      "createdAtUtc" timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      "updatedAtUtc" timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      "rowVersion" bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_events_context UNIQUE ("eventId", "academicTermId"),
      CONSTRAINT uq_events_code UNIQUE ("eventCode"),
      CONSTRAINT fk_events_term FOREIGN KEY ("academicTermId")
        REFERENCES "AcademicTerms" ("academicTermId"),
      CONSTRAINT fk_events_creator FOREIGN KEY ("createdByUserId")
        REFERENCES "Users" ("userId"),
      CONSTRAINT ck_events_status CHECK (
        "eventStatusCode" IN ('DRAFT', 'PUBLISHED', 'CLOSED', 'CANCELLED')
      )
    );

CREATE TABLE IF NOT EXISTS "EventSessions" (
      "eventSessionId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "eventId" bigint NOT NULL,
      "academicTermId" bigint NOT NULL,
      "sessionCode" varchar(30) NOT NULL,
      "sessionName" varchar(100) NOT NULL,
      "startsAtUtc" timestamptz(3) NOT NULL,
      "endsAtUtc" timestamptz(3) NOT NULL,
      "checkInOpensAtUtc" timestamptz(3) NOT NULL,
      "checkInClosesAtUtc" timestamptz(3) NOT NULL,
      "lateAfterUtc" timestamptz(3) NOT NULL,
      "checkOutOpensAtUtc" timestamptz(3) NOT NULL,
      "checkOutClosesAtUtc" timestamptz(3) NOT NULL,
      "requiresCheckOut" boolean NOT NULL DEFAULT true,
      "minimumMinutes" integer NOT NULL DEFAULT 0,
      "isClosed" boolean NOT NULL DEFAULT false,
      "sortOrder" integer NOT NULL DEFAULT 0,
      "createdAtUtc" timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      "rowVersion" bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_event_sessions_context UNIQUE ("eventSessionId", "academicTermId"),
      CONSTRAINT uq_event_sessions_code UNIQUE ("eventId", "sessionCode"),
      CONSTRAINT fk_event_sessions_event FOREIGN KEY ("eventId", "academicTermId")
        REFERENCES "Events" ("eventId", "academicTermId") ON DELETE CASCADE,
      CONSTRAINT ck_event_sessions_dates CHECK (
        "startsAtUtc" < "endsAtUtc"
        AND "checkInOpensAtUtc" <= "startsAtUtc"
        AND "checkInClosesAtUtc" >= "startsAtUtc"
        AND "checkInClosesAtUtc" <= "endsAtUtc"
        AND "lateAfterUtc" >= "startsAtUtc"
        AND "lateAfterUtc" <= "checkInClosesAtUtc"
        AND "checkOutOpensAtUtc" >= "startsAtUtc"
        AND "checkOutOpensAtUtc" <= "checkOutClosesAtUtc"
        AND "checkOutClosesAtUtc" >= "endsAtUtc"
      ),
      CONSTRAINT ck_event_sessions_minutes CHECK (
        "minimumMinutes" >= 0 AND ("requiresCheckOut" = true OR "minimumMinutes" = 0)
      )
    );

CREATE TABLE IF NOT EXISTS "EventParticipants" (
      "eventParticipantId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "eventSessionId" bigint NOT NULL,
      "academicTermId" bigint NOT NULL,
      "studentEnrollmentId" bigint NOT NULL,
      "studentId" bigint NOT NULL,
      "isRequired" boolean NOT NULL DEFAULT true,
      "addedByUserId" integer NOT NULL,
      "addedAtUtc" timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      CONSTRAINT uq_event_participants_student_session UNIQUE ("eventSessionId", "studentId"),
      CONSTRAINT fk_event_participants_session FOREIGN KEY ("eventSessionId", "academicTermId")
        REFERENCES "EventSessions" ("eventSessionId", "academicTermId") ON DELETE CASCADE,
      CONSTRAINT fk_event_participants_enrollment FOREIGN KEY (
        "academicTermId", "studentEnrollmentId", "studentId"
      ) REFERENCES "StudentEnrollments" ("academicTermId", "studentEnrollmentId", "studentId")
        ON DELETE CASCADE,
      CONSTRAINT fk_event_participants_actor FOREIGN KEY ("addedByUserId")
        REFERENCES "Users" ("userId")
    );

CREATE INDEX IF NOT EXISTS ix_event_participants_student
      ON "EventParticipants" ("studentId", "eventSessionId");

CREATE TABLE IF NOT EXISTS "AttendanceRecords" (
      "attendanceRecordId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "eventParticipantId" bigint NOT NULL,
      "checkedInAtUtc" timestamptz(3) NULL,
      "checkedOutAtUtc" timestamptz(3) NULL,
      "isExcused" boolean NOT NULL DEFAULT false,
      "excuseReason" varchar(500) NULL,
      "lastChangedByUserId" integer NOT NULL,
      "lastChangedAtUtc" timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      "rowVersion" bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_attendance_records_participant UNIQUE ("eventParticipantId"),
      CONSTRAINT fk_attendance_records_participant FOREIGN KEY ("eventParticipantId")
        REFERENCES "EventParticipants" ("eventParticipantId") ON DELETE CASCADE,
      CONSTRAINT fk_attendance_records_actor FOREIGN KEY ("lastChangedByUserId")
        REFERENCES "Users" ("userId"),
      CONSTRAINT ck_attendance_records_order CHECK (
        "checkedOutAtUtc" IS NULL
        OR ("checkedInAtUtc" IS NOT NULL AND "checkedOutAtUtc" >= "checkedInAtUtc")
      ),
      CONSTRAINT ck_attendance_records_excuse CHECK (
        ("isExcused" = false AND "excuseReason" IS NULL)
        OR (
          "isExcused" = true
          AND "excuseReason" IS NOT NULL
          AND char_length(btrim("excuseReason")) > 0
        )
      )
    );

CREATE TABLE IF NOT EXISTS "AttendanceCorrections" (
      "attendanceCorrectionId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "attendanceRecordId" bigint NOT NULL,
      "expectedRowVersion" bytea NOT NULL,
      "proposedCheckInAtUtc" timestamptz(3) NULL,
      "proposedCheckOutAtUtc" timestamptz(3) NULL,
      "proposedIsExcused" boolean NOT NULL,
      "proposedExcuseReason" varchar(500) NULL,
      reason varchar(1000) NOT NULL,
      "requestedByUserId" integer NOT NULL,
      "requestedAtUtc" timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      "correctionStatusCode" varchar(10) NOT NULL DEFAULT 'PENDING',
      "reviewedByUserId" integer NULL,
      "reviewedAtUtc" timestamptz(3) NULL,
      "reviewNote" varchar(1000) NULL,
      "rowVersion" bytea NOT NULL DEFAULT new_row_version(),
      CONSTRAINT uq_attendance_corrections_context UNIQUE (
        "attendanceRecordId", "attendanceCorrectionId"
      ),
      CONSTRAINT fk_attendance_corrections_record FOREIGN KEY ("attendanceRecordId")
        REFERENCES "AttendanceRecords" ("attendanceRecordId") ON DELETE CASCADE,
      CONSTRAINT fk_attendance_corrections_requester FOREIGN KEY ("requestedByUserId")
        REFERENCES "Users" ("userId"),
      CONSTRAINT fk_attendance_corrections_reviewer FOREIGN KEY ("reviewedByUserId")
        REFERENCES "Users" ("userId"),
      CONSTRAINT ck_attendance_corrections_status CHECK (
        "correctionStatusCode" IN ('PENDING', 'APPLIED', 'REJECTED')
      ),
      CONSTRAINT ck_attendance_corrections_reason CHECK (char_length(btrim(reason)) > 0),
      CONSTRAINT ck_attendance_corrections_order CHECK (
        "proposedCheckOutAtUtc" IS NULL
        OR (
          "proposedCheckInAtUtc" IS NOT NULL
          AND "proposedCheckOutAtUtc" >= "proposedCheckInAtUtc"
        )
      ),
      CONSTRAINT ck_attendance_corrections_excuse CHECK (
        ("proposedIsExcused" = false AND "proposedExcuseReason" IS NULL)
        OR (
          "proposedIsExcused" = true
          AND "proposedExcuseReason" IS NOT NULL
          AND char_length(btrim("proposedExcuseReason")) > 0
        )
      ),
      CONSTRAINT ck_attendance_corrections_review CHECK (
        ("correctionStatusCode" = 'PENDING' AND "reviewedByUserId" IS NULL AND "reviewedAtUtc" IS NULL)
        OR (
          "correctionStatusCode" IN ('APPLIED', 'REJECTED')
          AND "reviewedByUserId" IS NOT NULL
          AND "reviewedAtUtc" IS NOT NULL
          AND "reviewedAtUtc" >= "requestedAtUtc"
          AND "reviewedByUserId" <> "requestedByUserId"
        )
      )
    );

CREATE INDEX IF NOT EXISTS ix_attendance_corrections_queue
      ON "AttendanceCorrections" ("correctionStatusCode", "requestedAtUtc");

CREATE TABLE IF NOT EXISTS "AttendanceLogs" (
      "attendanceLogId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "attendanceRecordId" bigint NOT NULL,
      "attendanceCorrectionId" bigint NULL,
      "actionCode" varchar(15) NOT NULL,
      "oldCheckInAtUtc" timestamptz(3) NULL,
      "oldCheckOutAtUtc" timestamptz(3) NULL,
      "newCheckInAtUtc" timestamptz(3) NULL,
      "newCheckOutAtUtc" timestamptz(3) NULL,
      "oldIsExcused" boolean NULL,
      "newIsExcused" boolean NOT NULL DEFAULT false,
      "oldExcuseReason" varchar(500) NULL,
      "newExcuseReason" varchar(500) NULL,
      "actorUserId" integer NOT NULL,
      "recordedAtUtc" timestamptz(3) NOT NULL DEFAULT clock_timestamp(),
      "deviceNote" varchar(200) NULL,
      "isCancelled" boolean NOT NULL DEFAULT false,
      CONSTRAINT fk_attendance_logs_record FOREIGN KEY ("attendanceRecordId")
        REFERENCES "AttendanceRecords" ("attendanceRecordId") ON DELETE CASCADE,
      CONSTRAINT fk_attendance_logs_correction FOREIGN KEY (
        "attendanceRecordId", "attendanceCorrectionId"
      ) REFERENCES "AttendanceCorrections" ("attendanceRecordId", "attendanceCorrectionId"),
      CONSTRAINT fk_attendance_logs_actor FOREIGN KEY ("actorUserId")
        REFERENCES "Users" ("userId"),
      CONSTRAINT ck_attendance_logs_action CHECK ("actionCode" IN ('CHECK_IN', 'CHECK_OUT', 'CORRECTION')),
      CONSTRAINT ck_attendance_logs_correction CHECK (
        ("actionCode" = 'CORRECTION' AND "attendanceCorrectionId" IS NOT NULL)
        OR ("actionCode" IN ('CHECK_IN', 'CHECK_OUT') AND "attendanceCorrectionId" IS NULL)
      )
    );

CREATE INDEX IF NOT EXISTS ix_attendance_logs_record
      ON "AttendanceLogs" ("attendanceRecordId", "attendanceLogId");

CREATE INDEX IF NOT EXISTS ix_attendance_logs_lookup
      ON "AttendanceLogs" ("recordedAtUtc");

CREATE OR REPLACE VIEW "AttendanceSessionStatus" AS
     SELECT
       r."attendanceRecordId",
       ep."eventSessionId",
       ep."studentId",
       ep."studentEnrollmentId",
       r."checkedInAtUtc",
       r."checkedOutAtUtc",
       r."isExcused",
       r."excuseReason",
       CASE
         WHEN r."isExcused" THEN 'EXCUSED'
         WHEN r."checkedInAtUtc" IS NULL THEN 'ABSENT'
         WHEN r."checkedInAtUtc" > es."lateAfterUtc" THEN 'LATE'
         ELSE 'PRESENT'
       END AS "attendanceStatusCode",
       CASE
         WHEN r."checkedInAtUtc" IS NOT NULL AND r."checkedOutAtUtc" IS NOT NULL
           THEN floor(extract(epoch FROM (r."checkedOutAtUtc" - r."checkedInAtUtc")) / 60)::int
         ELSE NULL
       END AS "minutesPresent"
     FROM "AttendanceRecords" r
     JOIN "EventParticipants" ep ON ep."eventParticipantId" = r."eventParticipantId"
     JOIN "EventSessions" es ON es."eventSessionId" = ep."eventSessionId";

INSERT INTO ssc."AuthProviders" ("providerCode", "displayName")
VALUES
  ('google', 'Google'),
  ('microsoft', 'Microsoft'),
  ('apple', 'Apple')
ON CONFLICT ("providerCode") DO NOTHING;

INSERT INTO ssc."AcademicYears" ("yearCode", "yearName", "startsOn", "endsOn", "isActive")
VALUES
  ('DEFAULT', 'Default Academic Year', DATE '2020-01-01', DATE '2039-12-31', true),
  ('2025-2026', 'Academic Year 2025–2026', DATE '2025-08-01', DATE '2026-07-31', false),
  ('2026-2027', 'Academic Year 2026–2027', DATE '2026-08-01', DATE '2027-07-31', true)
ON CONFLICT ("yearCode") DO NOTHING;

INSERT INTO ssc."AcademicTerms" (
    "academicYearId", "termCode", "termName", "startsOn", "endsOn", "isActive"
)
SELECT y."academicYearId", v.term_code, v.term_name, v.starts_on, v.ends_on, v.is_active
FROM (
  VALUES
    ('DEFAULT', 'DEFAULT', 'Default Term', DATE '2020-01-01', DATE '2039-12-31', true),
    ('2025-2026', '2025-1S', 'First Semester', DATE '2025-08-04', DATE '2025-12-19', false),
    ('2025-2026', '2025-2S', 'Second Semester', DATE '2026-01-05', DATE '2026-05-15', false),
    ('2025-2026', '2025-MID', 'Midyear', DATE '2026-06-01', DATE '2026-07-24', false),
    ('2026-2027', '2026-1S', 'First Semester', DATE '2026-08-03', DATE '2026-12-18', true),
    ('2026-2027', '2026-2S', 'Second Semester', DATE '2027-01-05', DATE '2027-05-14', false),
    ('2026-2027', '2026-MID', 'Midyear', DATE '2027-06-01', DATE '2027-07-23', false)
) AS v(year_code, term_code, term_name, starts_on, ends_on, is_active)
JOIN ssc."AcademicYears" y ON y."yearCode" = v.year_code
ON CONFLICT ("academicYearId", "termCode") DO NOTHING;

INSERT INTO ssc."AcademicPrograms" ("programCode", "programName")
VALUES
  ('GEN', 'General'),
  ('BSIT', 'Bachelor of Science in Information Technology'),
  ('BSCS', 'Bachelor of Science in Computer Science'),
  ('BSCPE', 'Bachelor of Science in Computer Engineering'),
  ('BSIS', 'Bachelor of Science in Information Systems'),
  ('ACT', 'Associate in Computer Technology'),
  ('BSBA', 'Bachelor of Science in Business Administration'),
  ('BSHM', 'Bachelor of Science in Hospitality Management'),
  ('BSTM', 'Bachelor of Science in Tourism Management')
ON CONFLICT ("programCode") DO NOTHING;
