import type { DatabaseMigration } from './types.ts';

export const eventContributions: DatabaseMigration = {
  version: 2,
  name: 'event_contributions',
  sourceUrls: [import.meta.url],
  async up(db) {
    await db.query(`ALTER TABLE "EventRegistrations"
      ADD CONSTRAINT uq_registration_contribution_context UNIQUE ("eventRegistrationId", "eventId")`);
    await db.query(`CREATE TABLE "EventContributionTypes" (
      "contributionTypeId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "eventId" bigint NOT NULL REFERENCES "Events" ("eventId"),
      name varchar(200) NOT NULL CHECK (length(btrim(name)) > 0),
      "defaultAmount" numeric(12,2) NOT NULL CHECK ("defaultAmount" > 0),
      "dueDate" date NULL,
      "isRequired" boolean NOT NULL DEFAULT true,
      "createdByUserId" integer NOT NULL REFERENCES "Users" ("userId"),
      "createdAtUtc" timestamptz NOT NULL DEFAULT clock_timestamp(),
      UNIQUE ("eventId", name),
      UNIQUE ("contributionTypeId", "eventId")
    )`);
    await db.query(`CREATE TABLE "StudentContributions" (
      "studentContributionId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "eventId" bigint NOT NULL,
      "eventRegistrationId" bigint NOT NULL,
      "contributionTypeId" bigint NOT NULL,
      "amountDue" numeric(12,2) NOT NULL CHECK ("amountDue" > 0),
      "waiverAmount" numeric(12,2) NOT NULL DEFAULT 0 CHECK ("waiverAmount" >= 0 AND "waiverAmount" <= "amountDue"),
      "waiverReason" varchar(1000) NULL,
      "waivedByUserId" integer NULL REFERENCES "Users" ("userId"),
      "waivedAtUtc" timestamptz NULL,
      "assignedByUserId" integer NOT NULL REFERENCES "Users" ("userId"),
      "assignedAtUtc" timestamptz NOT NULL DEFAULT clock_timestamp(),
      UNIQUE ("eventRegistrationId", "contributionTypeId"),
      FOREIGN KEY ("eventRegistrationId", "eventId") REFERENCES "EventRegistrations" ("eventRegistrationId", "eventId"),
      FOREIGN KEY ("contributionTypeId", "eventId") REFERENCES "EventContributionTypes" ("contributionTypeId", "eventId"),
      CHECK ("waiverAmount" = 0 OR ("waiverReason" IS NOT NULL AND length(btrim("waiverReason")) > 0 AND "waivedByUserId" IS NOT NULL AND "waivedAtUtc" IS NOT NULL))
    )`);
    await db.query(`CREATE INDEX ix_student_contributions_event ON "StudentContributions" ("eventId")`);
    await db.query(`CREATE TABLE "ContributionPayments" (
      "contributionPaymentId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "studentContributionId" bigint NOT NULL REFERENCES "StudentContributions" ("studentContributionId"),
      amount numeric(12,2) NOT NULL CHECK (amount > 0),
      "paymentMethodCode" varchar(30) NOT NULL CHECK ("paymentMethodCode" IN ('CASH', 'GCASH', 'BANK_TRANSFER', 'OTHER')),
      "paymentReference" varchar(100) NOT NULL UNIQUE CHECK (length(btrim("paymentReference")) > 0),
      "externalPaymentReference" varchar(100) NULL,
      "paymentStatusCode" varchar(20) NOT NULL DEFAULT 'CONFIRMED' CHECK ("paymentStatusCode" IN ('CONFIRMED', 'VOIDED')),
      "receivedByUserId" integer NOT NULL REFERENCES "Users" ("userId"),
      "receivedAtUtc" timestamptz NOT NULL DEFAULT clock_timestamp(),
      "voidedByUserId" integer NULL REFERENCES "Users" ("userId"),
      "voidedAtUtc" timestamptz NULL,
      "voidReason" varchar(1000) NULL,
      CHECK ("paymentStatusCode" <> 'VOIDED' OR ("voidedByUserId" IS NOT NULL AND "voidedAtUtc" IS NOT NULL AND "voidReason" IS NOT NULL AND length(btrim("voidReason")) > 0))
    )`);
    await db.query(`CREATE INDEX ix_contribution_payments_student ON "ContributionPayments" ("studentContributionId")`);
    await db.query(`CREATE UNIQUE INDEX ux_contribution_payments_external_reference
      ON "ContributionPayments" ("paymentMethodCode", "externalPaymentReference") WHERE "externalPaymentReference" IS NOT NULL`);
    await db.query(`CREATE VIEW "VwStudentContributionBalances" AS
      SELECT sc.*, COALESCE(p.paid, 0)::numeric(12,2) AS "paidAmount",
        (sc."amountDue" - sc."waiverAmount" - COALESCE(p.paid, 0))::numeric(12,2) AS "outstandingAmount",
        CASE WHEN sc."waiverAmount" = sc."amountDue" THEN 'WAIVED'
          WHEN sc."amountDue" - sc."waiverAmount" = COALESCE(p.paid, 0) THEN 'PAID'
          WHEN COALESCE(p.paid, 0) > 0 THEN 'PARTIALLY_PAID' ELSE 'UNPAID' END AS status
      FROM "StudentContributions" sc LEFT JOIN LATERAL (
        SELECT SUM(amount) AS paid FROM "ContributionPayments" cp
        WHERE cp."studentContributionId" = sc."studentContributionId" AND cp."paymentStatusCode" = 'CONFIRMED'
      ) p ON true`);
  },
};
